name = "websocket-broadcast"
main = "src/chat-room.js"
compatibility_date = "2025-07-29"

[[durable_objects]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[build]
command = ""

[[routes]]
pattern = "yourdomain.com/ws/:room"
script = "websocket-broadcast"
