name = "ws"
main = "src/ws.js"
compatibility_date = "2025-07-29"

[durable_objects]
bindings = [
  { name = "WS_ROOM", class_name = "wsRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "wsRoom" ]
